### ISSUE TITLE
Can't run a map

### ISSUE THREAD

**Issue by GetLocalPlayer** [wurstscript/wurst4vscode#53]
Each time I tried to run a map I got
```
java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Unhandled method workspace/configuration
```
Building is always successful. Have I forgotten something?

**Comment by Frotty** [comment]
Provide complete `languageServer.log` and vscode output tab contents.

**Comment by GetLocalPlayer** [comment]
<details>
```
Loading Wurst version 1.8.1.0-jenkins-Wurst-1183
initialization done!
��� 12, 2019 8:53:29 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Unhandled method workspace/configuration
java.util.concurrent.CompletionException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Unhandled method workspace/configuration
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniApply(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.handleException(UserRequest.java:40)
	at de.peeeq.wurstio.languageserver.requests.MapRequest.handleException(MapRequest.java:79)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$handle$3(LanguageWorker.java:277)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:34)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$getNextWorkItem$1(LanguageWorker.java:171)
	at de.peeeq.wurstio.languageserver.LanguageWorker$Workitem.run(LanguageWorker.java:29)
	at de.peeeq.wurstio.languageserver.LanguageWorker.run(LanguageWorker.java:146)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Unhandled method workspace/configuration
	at de.peeeq.wurstio.languageserver.ConfigProvider.getConfig(ConfigProvider.java:44)
	at de.peeeq.wurstio.languageserver.ConfigProvider.getMapDocumentPath(ConfigProvider.java:56)
	at de.peeeq.wurstio.languageserver.requests.RunMap.findMapDocumentPath(RunMap.java:276)
	at de.peeeq.wurstio.languageserver.requests.RunMap.copyToWarcraftMapDir(RunMap.java:261)
	at de.peeeq.wurstio.languageserver.requests.RunMap.execute(RunMap.java:123)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:31)
	... 4 more
Caused by: java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Unhandled method workspace/configuration
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at de.peeeq.wurstio.languageserver.ConfigProvider.getConfig(ConfigProvider.java:30)
	... 9 more
Caused by: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Unhandled method workspace/configuration
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:209)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:192)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	... 1 more

```
</details>
[languageServer.log](https://github.com/wurstscript/wurst4vscode/files/3387308/languageServer.log)
